천재인가봐_기획_UI_추가
Mankik/season2 pull request #6
Opened 2023-11-01 06:20 UTC by nsa06035

천재인가봐_기획_UI

2023-11-01 10:00 UTC, black7375 approved these changes
UI와 서비스 구성을 매우 깔끔하게 잘 정리하셨네요 :+1:

2023-11-01 10:02 UTC, black7375 requested changes
다만, 파일 위치를 `docs/report/천재인가봐`쪽으로 옮겨주시면 될 것 같습니다.

https://github.com/nsa06035/season2/tree/%EC%B2%9C%EC%9E%AC%EC%9D%B8%EA%B0%80%EB%B4%90_%EA%B8%B0%ED%9A%8D_UI/docs/report/%EC%B2%9C%EC%9E%AC%EC%9D%B8%EA%B0%80%EB%B4%90

2023-11-02 13:02 UTC, nsa06035 commented
파일 위치를 옮기는 방법이 따로 있을까요?
아니면 pull Request를 다시 해야 하나요?

2023-11-02 13:46 UTC, merged

2023-11-02 13:49 UTC, black7375 commented
제가 일단 옮겨놓을게요!! 원격에서는 아무래도 명령어 세팅등이 힘들다보니, 다음에 한번 설명드리도록 하겠습니다.